// Realistic Indian Tech Job Dataset
const jobsData = [
    {
        id: 1,
        title: "SDE Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Data Structures", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹40k–₹50k/month Internship",
        applyUrl: "https://amazon.jobs/en/jobs/intern-sde",
        description: "Join Amazon's engineering team as an SDE Intern. Work on scalable systems and learn from experienced engineers. Strong problem-solving skills required. Opportunity to convert to full-time role."
    },
    {
        id: 2,
        title: "Graduate Engineer Trainee",
        company: "Infosys",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Python", "SQL"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "3.5–4.5 LPA",
        applyUrl: "https://infosys.com/careers/get",
        description: "Infosys is hiring fresh graduates for our engineering program. Comprehensive training provided. Work on client projects across domains. Great learning opportunity for career growth."
    },
    {
        id: 3,
        title: "Frontend Intern",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "JavaScript", "HTML", "CSS"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://razorpay.com/jobs/frontend-intern",
        description: "Build beautiful user interfaces for India's leading payment gateway. Work with modern tech stack including React and TypeScript. Mentorship from senior engineers. Potential for PPO."
    },
    {
        id: 4,
        title: "QA Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Manual Testing", "Selenium", "Java"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹25k–₹35k/month Internship",
        applyUrl: "https://flipkart.com/careers/qa-intern",
        description: "Join Flipkart's quality assurance team. Learn testing methodologies and automation frameworks. Work on e-commerce platform testing. Hands-on experience with industry tools."
    },
    {
        id: 5,
        title: "Data Analyst Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "SQL", "Excel", "Tableau"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹30k–₹40k/month Internship",
        applyUrl: "https://swiggy.com/careers/data-analyst",
        description: "Analyze food delivery data and generate insights. Work with large datasets and visualization tools. Support business decisions with data-driven recommendations. Fast-paced startup environment."
    },
    {
        id: 6,
        title: "Java Developer",
        company: "TCS",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "3–5 LPA",
        applyUrl: "https://tcs.com/careers/java-developer",
        description: "Develop enterprise applications using Java and Spring framework. Work on banking and financial services projects. Training provided on latest technologies. Global exposure opportunities."
    },
    {
        id: 7,
        title: "Python Developer",
        company: "Wipro",
        location: "Chennai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "Django", "REST APIs"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "3.5–5 LPA",
        applyUrl: "https://wipro.com/careers/python-dev",
        description: "Build backend services using Python and Django. Work on cloud-based applications. Collaborate with global teams. Excellent learning and growth opportunities in a Fortune 500 company."
    },
    {
        id: 8,
        title: "React Developer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "Redux", "TypeScript", "Node.js"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "8–12 LPA",
        applyUrl: "https://phonepe.com/careers/react-developer",
        description: "Build India's most loved payment app. Work on features used by millions daily. Modern tech stack with React and TypeScript. Fast-paced fintech environment with great perks."
    },
    {
        id: 9,
        title: "Backend Developer Intern",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Node.js", "MongoDB", "Express"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹35k–₹50k/month Internship",
        applyUrl: "https://cred.club/careers/backend-intern",
        description: "Join CRED's engineering team. Build scalable backend systems for fintech products. Work with cutting-edge technologies. Mentorship from industry experts. High conversion rate to full-time."
    },
    {
        id: 10,
        title: "Graduate Engineer Trainee",
        company: "Accenture",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "C++", "Problem Solving"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "4–5 LPA",
        applyUrl: "https://accenture.com/careers/get",
        description: "Join Accenture's technology consulting team. Work on diverse client projects across industries. Comprehensive training program. International project opportunities. Strong career progression path."
    },
    {
        id: 11,
        title: "SDE Intern",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Python", "Data Structures"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://paytm.com/careers/sde-intern",
        description: "Work on India's leading digital payments platform. Build features for millions of users. Learn from experienced engineers. Exposure to fintech domain. PPO based on performance."
    },
    {
        id: 12,
        title: "Full Stack Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Node.js", "MySQL", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "6–10 LPA",
        applyUrl: "https://zoho.com/careers/fullstack",
        description: "Build SaaS products used by millions globally. Work on both frontend and backend. Product-based company with no client work. Excellent work-life balance and learning culture."
    },
    {
        id: 13,
        title: "QA Engineer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Remote",
        experience: "0-1",
        skills: ["Selenium", "Java", "API Testing"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "4–6 LPA",
        applyUrl: "https://freshworks.com/careers/qa-engineer",
        description: "Ensure quality of SaaS products. Automate testing processes. Work with agile teams. Remote-first culture. Stock options and competitive benefits. Fast-growing unicorn startup."
    },
    {
        id: 14,
        title: "Data Analyst",
        company: "Juspay",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["SQL", "Python", "Power BI", "Statistics"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "7–11 LPA",
        applyUrl: "https://juspay.in/careers/data-analyst",
        description: "Analyze payment transaction data. Build dashboards and reports. Work with product and engineering teams. Fintech domain expertise. Solve interesting data problems at scale."
    },
    {
        id: 15,
        title: "Junior Backend Developer",
        company: "Capgemini",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring", "Microservices"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "3.5–5.5 LPA",
        applyUrl: "https://capgemini.com/careers/backend-dev",
        description: "Develop microservices for enterprise clients. Work on cloud-native applications. Training on latest frameworks. Global project exposure. Strong technical mentorship program."
    },
    {
        id: 16,
        title: "Frontend Developer",
        company: "Cognizant",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Angular", "TypeScript", "HTML", "CSS"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "5–8 LPA",
        applyUrl: "https://cognizant.com/careers/frontend",
        description: "Build responsive web applications for Fortune 500 clients. Work with modern frontend frameworks. Agile development environment. Opportunity to work on diverse projects across domains."
    },
    {
        id: 17,
        title: "SDE Intern",
        company: "IBM",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C++", "Python", "Cloud Computing"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹35k–₹45k/month Internship",
        applyUrl: "https://ibm.com/careers/intern-sde",
        description: "Join IBM's cloud and AI division. Work on enterprise software solutions. Access to cutting-edge technology. Mentorship from industry veterans. Strong brand value for career."
    },
    {
        id: 18,
        title: "Graduate Engineer Trainee",
        company: "Oracle",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Database Systems"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "4–6 LPA",
        applyUrl: "https://oracle.com/careers/get",
        description: "Work on Oracle's database and cloud products. Comprehensive training on enterprise technologies. Global career opportunities. Work with cutting-edge database systems. Strong technical foundation."
    },
    {
        id: 19,
        title: "React Native Developer",
        company: "Dunzo",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["React Native", "JavaScript", "Mobile Development"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "7–12 LPA",
        applyUrl: "https://dunzo.com/careers/react-native",
        description: "Build mobile apps for quick commerce platform. Work on features used by thousands daily. Modern tech stack. Fast-paced startup culture. ESOPs and competitive compensation."
    },
    {
        id: 20,
        title: "DevOps Intern",
        company: "SAP",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Linux", "Docker", "Jenkins", "AWS"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "₹30k–₹40k/month Internship",
        applyUrl: "https://sap.com/careers/devops-intern",
        description: "Learn DevOps practices at enterprise scale. Work with CI/CD pipelines and cloud infrastructure. Hands-on experience with industry-standard tools. Mentorship from DevOps experts."
    },
    {
        id: 21,
        title: "Java Developer",
        company: "Dell",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "REST APIs"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "4–6 LPA",
        applyUrl: "https://dell.com/careers/java-developer",
        description: "Develop enterprise software solutions. Work on Dell's internal tools and platforms. Collaborative work environment. Access to latest technologies. Strong employee benefits and work culture."
    },
    {
        id: 22,
        title: "Python Developer",
        company: "Meesho",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Python", "Django", "PostgreSQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "8–14 LPA",
        applyUrl: "https://meesho.com/careers/python-dev",
        description: "Build backend systems for India's fastest-growing e-commerce platform. Work on high-scale distributed systems. Modern tech stack. Unicorn startup with strong growth trajectory."
    },
    {
        id: 23,
        title: "Frontend Intern",
        company: "Ola",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["React", "JavaScript", "CSS"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://ola.com/careers/frontend-intern",
        description: "Build user interfaces for Ola's mobility platform. Work on features impacting millions of rides. Learn from experienced frontend engineers. Fast-paced product development environment."
    },
    {
        id: 24,
        title: "Data Engineer",
        company: "Myntra",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Python", "Spark", "Hadoop", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "9–15 LPA",
        applyUrl: "https://myntra.com/careers/data-engineer",
        description: "Build data pipelines for fashion e-commerce. Work with big data technologies. Process millions of transactions daily. Solve interesting data engineering challenges at scale."
    },
    {
        id: 25,
        title: "Mobile Developer Intern",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Android", "Kotlin", "Java"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://zomato.com/careers/mobile-intern",
        description: "Develop features for Zomato's food delivery app. Work on Android platform. Learn mobile development best practices. Impact millions of food lovers. High PPO conversion rate."
    },
    {
        id: 26,
        title: "Backend Developer",
        company: "Groww",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Go", "Microservices", "Kubernetes", "MySQL"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–18 LPA",
        applyUrl: "https://groww.in/careers/backend-dev",
        description: "Build scalable backend for India's fastest-growing investment platform. Work with modern tech stack including Go and Kubernetes. Fintech domain. Unicorn startup with great culture."
    },
    {
        id: 27,
        title: "QA Automation Engineer",
        company: "Nykaa",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Selenium", "Python", "API Testing"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "4–7 LPA",
        applyUrl: "https://nykaa.com/careers/qa-automation",
        description: "Automate testing for beauty e-commerce platform. Build test frameworks and CI/CD integration. Work with agile teams. E-commerce domain expertise. Listed unicorn company."
    },
    {
        id: 28,
        title: "Full Stack Intern",
        company: "Udaan",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "Node.js", "MongoDB"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹35k–₹50k/month Internship",
        applyUrl: "https://udaan.com/careers/fullstack-intern",
        description: "Work on B2B e-commerce platform. Build features for traders and retailers. Full stack development exposure. Learn from experienced engineers. Unicorn startup environment."
    },
    {
        id: 29,
        title: "Java Developer",
        company: "Mindtree",
        location: "Pune",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "Spring", "Hibernate", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "5–9 LPA",
        applyUrl: "https://mindtree.com/careers/java-dev",
        description: "Develop enterprise applications for global clients. Work on digital transformation projects. Agile methodology. International exposure. Strong technical training programs."
    },
    {
        id: 30,
        title: "Frontend Developer",
        company: "Postman",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "TypeScript", "GraphQL"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "12–20 LPA",
        applyUrl: "https://postman.com/careers/frontend",
        description: "Build the world's leading API platform. Work on developer tools used by millions. Modern tech stack. Remote-first culture. Unicorn startup with global presence. Stock options."
    },
    {
        id: 31,
        title: "SDE Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Python", "Data Structures"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹40k–₹55k/month Internship",
        applyUrl: "https://flipkart.com/careers/sde-intern",
        description: "Join India's leading e-commerce company. Work on large-scale distributed systems. Solve challenging technical problems. Mentorship from senior engineers. High conversion to full-time."
    },
    {
        id: 32,
        title: "Data Scientist Intern",
        company: "Walmart Labs",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Machine Learning", "Statistics"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹40k–₹50k/month Internship",
        applyUrl: "https://walmart.com/careers/data-science-intern",
        description: "Apply ML to retail problems. Work with large datasets. Learn from data science experts. Access to cutting-edge tools and technologies. Global retail giant's innovation lab."
    },
    {
        id: 33,
        title: "Backend Engineer",
        company: "ShareChat",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Python", "Django", "Redis", "PostgreSQL"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "8–14 LPA",
        applyUrl: "https://sharechat.com/careers/backend",
        description: "Build backend for India's largest social media platform. Work on features used by 180M+ users. High-scale systems. Modern tech stack. Unicorn startup with strong growth."
    },
    {
        id: 34,
        title: "iOS Developer",
        company: "Dream11",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Swift", "iOS", "Mobile Development"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "9–16 LPA",
        applyUrl: "https://dream11.com/careers/ios-developer",
        description: "Develop iOS app for India's biggest fantasy sports platform. Work on features for millions of users. Modern iOS development practices. Sports-tech domain. Unicorn company."
    },
    {
        id: 35,
        title: "Graduate Engineer Trainee",
        company: "Tech Mahindra",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "C++", "SQL"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "3.5–4.5 LPA",
        applyUrl: "https://techmahindra.com/careers/get",
        description: "Join Tech Mahindra's engineering program. Work on telecom and IT projects. Comprehensive training. Global client exposure. Strong career growth opportunities in Mahindra group."
    },
    {
        id: 36,
        title: "React Developer",
        company: "Licious",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "Redux", "JavaScript"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "7–12 LPA",
        applyUrl: "https://licious.in/careers/react-dev",
        description: "Build e-commerce platform for fresh meat and seafood. Work on customer-facing features. Modern frontend stack. D2C startup with strong funding. Fast-paced environment."
    },
    {
        id: 37,
        title: "DevOps Engineer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["AWS", "Kubernetes", "Terraform", "Python"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "10–18 LPA",
        applyUrl: "https://razorpay.com/careers/devops",
        description: "Manage infrastructure for India's leading payment gateway. Work with cloud-native technologies. High-scale systems. Fintech domain. Unicorn startup with excellent culture."
    },
    {
        id: 38,
        title: "QA Intern",
        company: "Byju's",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Manual Testing", "Selenium", "Java"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://byjus.com/careers/qa-intern",
        description: "Test ed-tech platform used by millions of students. Learn QA methodologies and automation. Work on mobile and web testing. Ed-tech domain. India's largest ed-tech company."
    },
    {
        id: 39,
        title: "Full Stack Developer",
        company: "Cure.fit",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "Node.js", "AWS", "MongoDB"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "8–13 LPA",
        applyUrl: "https://curefit.com/careers/fullstack",
        description: "Build health and fitness platform. Work on both web and mobile features. Modern tech stack. Health-tech domain. Unicorn startup with mission-driven culture."
    },
    {
        id: 40,
        title: "Backend Developer Intern",
        company: "Unacademy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Node.js", "Express", "MongoDB"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://unacademy.com/careers/backend-intern",
        description: "Work on India's largest learning platform. Build scalable backend services. Ed-tech domain. Learn from experienced engineers. Unicorn startup with strong growth."
    },
    {
        id: 41,
        title: "Android Developer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Android", "Kotlin", "Java", "MVVM"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "https://phonepe.com/careers/android",
        description: "Develop Android app for India's most loved payment platform. Work on features used by 400M+ users. Modern Android development. Fintech domain. Walmart-backed unicorn."
    },
    {
        id: 42,
        title: "Data Analyst",
        company: "Urban Company",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["SQL", "Python", "Excel", "Tableau"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "5–8 LPA",
        applyUrl: "https://urbancompany.com/careers/data-analyst",
        description: "Analyze service marketplace data. Build dashboards and reports. Support business decisions with insights. On-demand services domain. Unicorn startup with pan-India presence."
    },
    {
        id: 43,
        title: "Frontend Developer",
        company: "Vedantu",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "JavaScript", "WebRTC"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "6–11 LPA",
        applyUrl: "https://vedantu.com/careers/frontend",
        description: "Build live learning platform. Work on video streaming and interactive features. Ed-tech domain. Modern frontend technologies. Mission-driven startup impacting education."
    },
    {
        id: 44,
        title: "Java Developer",
        company: "HCL Technologies",
        location: "Noida",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring", "Microservices"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "3.5–5.5 LPA",
        applyUrl: "https://hcltech.com/careers/java-dev",
        description: "Develop enterprise applications for global clients. Work on digital transformation projects. Training on modern frameworks. International project opportunities. Strong IT services company."
    },
    {
        id: 45,
        title: "Python Developer",
        company: "Ola Electric",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "FastAPI", "PostgreSQL", "Docker"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "8–14 LPA",
        applyUrl: "https://olaelectric.com/careers/python",
        description: "Build software for electric vehicles. Work on IoT and connected car features. EV domain. Modern tech stack. Mission-driven company building future of mobility."
    },
    {
        id: 46,
        title: "SDE Intern",
        company: "Microsoft",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["C++", "Data Structures", "Algorithms"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "₹50k–₹80k/month Internship",
        applyUrl: "https://microsoft.com/careers/intern-sde",
        description: "Join Microsoft's engineering team. Work on cloud and AI products. World-class mentorship. Access to cutting-edge technology. Strong brand value. High conversion to full-time."
    },
    {
        id: 47,
        title: "Full Stack Developer",
        company: "Delhivery",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Node.js", "MySQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "7–12 LPA",
        applyUrl: "https://delhivery.com/careers/fullstack",
        description: "Build logistics and supply chain platform. Work on tracking and optimization systems. Modern tech stack. Logistics-tech domain. Listed unicorn company."
    },
    {
        id: 48,
        title: "Machine Learning Intern",
        company: "Google",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "TensorFlow", "Machine Learning"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹80k–₹1L/month Internship",
        applyUrl: "https://google.com/careers/ml-intern",
        description: "Work on ML projects at Google. Access to world-class infrastructure and datasets. Mentorship from top researchers. Solve impactful problems. Prestigious internship opportunity."
    },
    {
        id: 49,
        title: "Backend Developer",
        company: "Rapido",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Go", "Microservices", "Redis", "Kafka"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "9–15 LPA",
        applyUrl: "https://rapido.bike/careers/backend",
        description: "Build backend for bike taxi platform. Work on real-time matching and routing. High-scale systems. Mobility-tech domain. Fast-growing unicorn startup."
    },
    {
        id: 50,
        title: "iOS Developer Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Swift", "iOS", "UIKit"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "₹35k–₹50k/month Internship",
        applyUrl: "https://swiggy.com/careers/ios-intern",
        description: "Develop iOS app for food delivery platform. Work on features for millions of users. Learn iOS development best practices. Fast-paced startup. High PPO conversion."
    },
    {
        id: 51,
        title: "Data Engineer",
        company: "Airtel",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Spark", "Hadoop", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "8–13 LPA",
        applyUrl: "https://airtel.in/careers/data-engineer",
        description: "Build data pipelines for telecom giant. Work with petabyte-scale data. Telecom domain. Modern data stack. India's leading telecom company with strong tech culture."
    },
    {
        id: 52,
        title: "Frontend Developer",
        company: "Polygon",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "Web3", "TypeScript"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–22 LPA",
        applyUrl: "https://polygon.technology/careers/frontend",
        description: "Build Web3 applications on Polygon blockchain. Work on decentralized apps. Crypto/blockchain domain. Cutting-edge technology. Global Web3 company. Stock options and crypto compensation."
    },
    {
        id: 53,
        title: "QA Engineer",
        company: "Salesforce",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Selenium", "Java", "API Testing", "CI/CD"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "5–8 LPA",
        applyUrl: "https://salesforce.com/careers/qa-engineer",
        description: "Test enterprise CRM platform. Automate testing workflows. Work with agile teams. Cloud computing domain. Global SaaS leader with excellent culture and benefits."
    },
    {
        id: 54,
        title: "Backend Developer",
        company: "Zerodha",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Python", "Go", "PostgreSQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "https://zerodha.com/careers/backend",
        description: "Build India's largest stock broking platform. Work on trading systems. Fintech domain. Modern tech stack. Bootstrapped profitable company. No-nonsense engineering culture."
    },
    {
        id: 55,
        title: "Full Stack Intern",
        company: "Atlassian",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["React", "Java", "Spring Boot"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "₹60k–₹80k/month Internship",
        applyUrl: "https://atlassian.com/careers/fullstack-intern",
        description: "Work on Jira, Confluence, or Trello. Build features for millions of users globally. World-class engineering culture. Mentorship from senior engineers. High conversion rate."
    },
    {
        id: 56,
        title: "Android Developer",
        company: "Hotstar",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Android", "Kotlin", "ExoPlayer", "MVVM"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "10–18 LPA",
        applyUrl: "https://hotstar.com/careers/android",
        description: "Develop Android app for India's largest streaming platform. Work on video streaming technology. Handle massive scale during live sports. OTT domain. Disney-backed company."
    },
    {
        id: 57,
        title: "DevOps Engineer",
        company: "Nutanix",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Kubernetes", "Docker", "AWS", "Python"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "9–16 LPA",
        applyUrl: "https://nutanix.com/careers/devops",
        description: "Manage cloud infrastructure for enterprise clients. Work with hybrid cloud technologies. DevOps best practices. Enterprise software domain. Global company with strong tech culture."
    },
    {
        id: 58,
        title: "Data Scientist",
        company: "Ola",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Python", "Machine Learning", "SQL", "Deep Learning"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–20 LPA",
        applyUrl: "https://ola.com/careers/data-scientist",
        description: "Apply ML to mobility problems. Build pricing and matching algorithms. Work with large-scale data. Mobility-tech domain. Solve interesting optimization problems."
    },
    {
        id: 59,
        title: "React Developer",
        company: "Stripe",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "TypeScript", "GraphQL", "Node.js"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "15–25 LPA",
        applyUrl: "https://stripe.com/careers/react-developer",
        description: "Build payment infrastructure for the internet. Work on developer tools and dashboards. Global fintech leader. Modern tech stack. Remote-first culture. Stock options and top compensation."
    },
    {
        id: 60,
        title: "Graduate Engineer Trainee",
        company: "L&T Infotech",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Python", "SQL"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "3.5–4.5 LPA",
        applyUrl: "https://lntinfotech.com/careers/get",
        description: "Join L&T's IT services division. Work on enterprise projects across domains. Comprehensive training program. Part of L&T group. Strong career growth opportunities."
    }
];
